[workspace]
members = [
    "dog-core",
    "dog-axum",
    "dog-typedb",
    "dog-blob",
    "dog-examples/music-blobs",
    "dog-schema",
    "dog-schema-macros",
    "dog-schema-validator",
    "dog-examples/blog-axum",
    "dog-examples/social-typedb",
]

resolver = "2"
