[package]
name = "dog-schema"
version = "0.1.0"
edition = "2021"

[dependencies]
dog-core = { path = "../dog-core", features = ["serde"] }
serde_json = "1.0.145"
anyhow = "1.0.100"

# Re-export proc macros
dog-schema-macros = { path = "../dog-schema-macros" }
