[package]
name = "dog-axum"
version = "0.1.0"
edition = "2021"
description = "A Rust library created with FerrisUp"
license = "MIT OR Apache-2.0"

[package.metadata]

[package.metadata.ferrisup]
component_type = "library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.8.7", features = ["macros", "json"] }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0.100"
async-trait = "0.1.89"
tracing = "0.1.41"
tower-http = { version = "0.6.6", features = ["trace", "request-id"] }
uuid = { version = "1.18.1", features = ["v4"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
dog-core = { path = "../dog-core", features = ["serde"] }

[dev-dependencies]
anyhow = "1.0.100"
tower = "0.5.2"
http-body-util = "0.1.3"

[lib]
name = "dog_axum"
path = "src/lib.rs"
