[package]
name = "dog-axum"
version = "0.1.0"
edition = "2021"
description = "A Rust library created with FerrisUp"
license = "MIT OR Apache-2.0"

[package.metadata]

[package.metadata.ferrisup]
component_type = "library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dog-core = { path = "../dog-core" }
axum = { version = "0.8.7", features = ["macros", "json"] }
[dev-dependencies]
anyhow = "1.0.100"

[lib]
name = "dog_axum"
path = "src/lib.rs"
