[package]
name = "social-typedb"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
dog-axum = { path = "../../dog-axum" }
dog-core = { path = "../../dog-core", features = ["serde", "adapters"] }
dog-typedb = { path = "../../dog-typedb" }
futures = "0.3.31"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "time"] }
tower-http = { version = "0.5", features = ["fs", "cors"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
typedb-driver = "3.7.0"

[lib]
name = "social_typedb"
path = "src/lib.rs"
